import type { StaffTicket, TechnicianTicket } from "./types";

export const staffTickets: StaffTicket[] = [
  {
    id: "INC-1048",
    type: "Device or equipment",
    title: "Front desk printer stops after each page",
    location: "Front Office",
    updated: "12 minutes ago",
    day: "30",
    month: "Aug",
    priority: "high",
    status: "Waiting for IT",
    state: "active",
  },
  {
    id: "REQ-1039",
    type: "Account or access",
    title: "Access to the weekly occupancy report",
    location: "Administration",
    updated: "yesterday",
    day: "29",
    month: "Aug",
    priority: "normal",
    status: "Needs your reply",
    state: "active",
  },
  {
    id: "INC-1027",
    type: "Network or Wi-Fi",
    title: "Weak Wi-Fi signal in the west lobby",
    location: "Main Lobby",
    updated: "2 days ago",
    day: "28",
    month: "Aug",
    priority: "normal",
    status: "In progress",
    state: "active",
  },
];

export const technicianTickets: TechnicianTicket[] = [
  {
    key: "pos",
    id: "INC-1051",
    priority: "P1",
    title: "POS terminals cannot connect",
    age: "8 min ago",
    location: "Main Restaurant",
    impact: "Guest-facing · 7 devices",
    owner: "Jamie",
    ownerInitials: "JD",
    sla: "18 min",
    slaState: "danger",
    requester: "Maria Santos",
    lastUpdate: "4 minutes ago",
    device: "POS-RST-01",
    affected: "Seven terminals are currently affected",
    alerts: "3 active",
  },
  {
    key: "printer",
    id: "INC-1048",
    priority: "P2",
    title: "Front desk printer stops after each page",
    age: "24 min ago",
    location: "Front Office",
    impact: "Check-in affected",
    owner: "Unassigned",
    ownerInitials: "—",
    sla: "36 min",
    slaState: "warning",
    requester: "Alex Morgan",
    lastUpdate: "12 minutes ago",
    device: "PRN-FRO-02",
    affected: "Front Office check-in printing is affected",
    alerts: "1 active",
  },
  {
    key: "wifi",
    id: "ALT-1046",
    priority: "P2",
    title: "West lobby access point offline",
    age: "Level alert",
    location: "Main Lobby",
    impact: "AP-LBY-WEST-01",
    owner: "Samira",
    ownerInitials: "SK",
    sla: "1h 12m",
    slaState: "normal",
    requester: "Level.io monitor",
    lastUpdate: "Just now",
    device: "AP-LBY-WEST-01",
    affected: "Wireless coverage is reduced in the west lobby",
    alerts: "2 active",
  },
];
